# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdea7d16a0ca5c1940abe7bd44d95c7ae9201d68da88eabbcbc65b55ec555c0de0e99000380663d92782f8f0596061924ef00c82fa9a1758e769f04a30980ee6

test:
  secret_key_base: 492e4a7927f6362f06c20e05de5d737be6968a56a37ce9fed1fc8d2b2c5ef5e65cfd456626c4393860c5f53f33440400c4e6d1bd11f17037ed60adcca17d81c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
